
# vim-style pane navigation
# tmux.conf
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# mark pane with 'm', then go to the target pane and vertically/horizontally join
bind  H     join-pane -h
bind  V     join-pane -v

# new panes/windows open in cwd
bind  c     new-window      -c      "#{pane_current_path}"
bind  '"'   split-window    -v -c   "#{pane_current_path}"
bind  %     split-window    -h -c   "#{pane_current_path}"

bind  C-b   last-window
bind  b     send-prefix
bind  r     source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

bind  C-g   display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"
bind  C-t   display-popup -d "#{pane_current_path}" -w 90% -h 50% -E "zsh"

set   -g    base-index            1
set   -g    bell-action           none
set   -g    default-terminal      "tmux-256color"
set   -g    escape-time           0
set   -g    focus-events          on
set   -g    history-limit         100000
set   -g    mode-keys             vi
set   -g    mouse                 on
set   -g    renumber-windows      on
set   -g    status-justify        absolute-centre
set   -g    status-left           ""
set   -g    status-position       top
set   -g    status-right          "[#S]"
set   -g    status-style          "bg=default,fg=blue"
set   -g    window-size           largest
set   -ga   terminal-overrides    ",:RGB"
set   -ga   terminal-overrides    ",:usstyle"
setw  -g    pane-base-index       1

