FROM alpine:edge

RUN apk add --no-cache \
        aria2 \
        dumb-init \
        ffmpeg \
        imagemagick \
        mediainfo \
        yt-dlp \
    && printf '%s\n' '--no-cache-dir' > /etc/yt-dlp.conf

ENV HOME=/tmp
WORKDIR /data

ENTRYPOINT ["dumb-init", "--"]
CMD ["cat", "/etc/os-release"]
