#!/usr/bin/env zsh

# various environment variables and aliases

export MANPAGER='less -R --use-color -Dd+r -Du+b' # use colours in man pager

if (( $+commands[eza] )); then
  export EZA_CONFIG_DIR=$XDG_CONFIG_HOME/eza
  alias ls='eza --icons'
  alias la='eza -la --icons --git'
else
  alias la='ls -lah'
fi

if (( $+commands[nvim] )); then
  export EDITOR='nvim'
  alias vim='nvim'
else
  export EDITOR='vim'
fi

alias tmuxx="tmux new -As $(hostname)" # attach to existing or create new session

