#!/usr/bin/env zsh

# list files in a tree style output using `eza`.

# pass a number for $1 to replace the tree level
local level="3"

if [[ $1 == <-> ]]; then
  level=$1
  shift
fi

eza -lao --icons --no-permissions --git --tree -L$level $@

