#!/usr/bin/env zsh

for p in \
  "${HOME}/.cache/nvim" \
  "${HOME}/.local/share/nvim" \
  "${HOME}/.local/state/nvim" \
  "${HOME}/.config/nvim/nvim-pack-lock.json"; do
  rm -rf "$p"
  echo "removed $p"
done
