#!/usr/bin/env zsh

# prints the public IP address
local public_ip="$(curl -s -4 ifconfig.me | tr -d '\n')"
echo "$public_ip"

# if interactive session (not piped/redirected), copy public IP to macOS system clipboard
[[ $- == *i* && -t 1 ]] && printf "$public_ip" | pbcopy

