#!/usr/bin/env zsh

# rebuilds symlinks for dotfiles that reference `~`

local num_errors=0

_rebuild_symlink() {
  local src="$1"
  local dest="$2"

  if [[ -f "$src" ]]; then
    mkdir -p "${dest:h}"
    ln -sf "$src" "$dest"
    echo "INFO: created symlink: $dest -> $src"
  else
    echo "ERROR: missing file: $src" >&2
    (( num_errors++ ))
  fi
}


# --- bat theme ---
_rebuild_symlink \
  ~/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/sublime/tokyonight_night.tmTheme \
  ~/.config/bat/themes/tokyonight_night.tmTheme


# --- eza theme ---
_rebuild_symlink \
  ~/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/eza/tokyonight_night.yml \
  ~/.config/eza/theme.yml


# ---
if (( num_errors > 0 )); then
  return 1
fi

