#!/usr/bin/env zsh

# rebuilds symlinks for dotfiles that reference `~`

local num_errors=0

local eza_theme_yml=~/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/eza/tokyonight_night.yml

if [[ -f "$eza_theme_yml" ]]; then
  mkdir -p ~/.config/eza
  ln -sf "$eza_theme_yml" ~/.config/eza/theme.yml
else
  echo "ERROR: missing file: $eza_theme_yml" >&2
  (( num_errors++ ))
fi


if (( num_errors > 0 )); then
  echo "Symlinks recreated with $num_errors error(s)." >&2
  return 1
fi

