#!/usr/bin/env zsh

local num_errors=0

_rebuild_symlink() {
  local src="$1"
  local dest="$2"

  if [[ -f "$src" ]]; then
    mkdir -p "${dest:h}"
    ln -sf "$src" "$dest"
    echo "created symlink: $dest -> $src"
  else
    echo "missing file: $src" >&2
    ((num_errors++))
  fi
}

_save_url() {
  local src_url="$1"
  local dest_file="$2"
  local tmp_file="$(mktemp)"
  local dest_dir="${dest_file:h}"

  [[ -d "$dest_dir" ]] || mkdir -p "$dest_dir"

  echo "downloading: ${src_url}"
  if curl -fsSL -o "$tmp_file" "$src_url"; then
    rm -f "$dest_file"
    mv "$tmp_file" "$dest_file"
    echo "saved to: ${dest_file}"
  else
    echo "download failed: $src_url" >&2
    rm -f "$tmp_file"
    ((num_errors++))
  fi
}

_exists() {
  local ctype="$1"
  local target="$2"
  local found=0

  case "$ctype" in
    file | -f) [[ -f "$target" ]] && found=1 ;;
    dir | -d) [[ -d "$target" ]] && found=1 ;;
    cmd | -c) (($+commands[$target])) && found=1 ;;
    *)
      echo "ERROR: unknown check type '$ctype'" >&2
      ((num_errors++))
      return 1
      ;;
  esac

  if ((found)); then
    echo "exists: $target"
    return 0
  else
    echo "missing: $target" >&2
    return 1
  fi
}

_download_file_if_missing() {
  local theme_file="$1"
  local theme_url="$2"
  _exists -f "$theme_file" || _save_url "$theme_url" "$theme_file"
}

_download_file_if_missing ~/.config/eza/theme.yml 'https://raw.githubusercontent.com/eza-community/eza-themes/main/themes/catppuccin-mocha.yml'
_download_file_if_missing ~/.config/delta/theme.gitconfig 'https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig'

return $((num_errors > 0))
