#!/usr/bin/env zsh

# Run 'zsh_healthcheck' manually to verify your setup
local missing=0

# Define your critical tools here
local critical_cmds=(nvim eza fzf zoxide delta)
local critical_files=(
  # to be installed via homebrew (see ~/.config/brew)
  "${BREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
  "${BREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
  # to be installed via neovim plugin: https://github.com/folke/tokyonight.nvim
  "${HOME}/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/delta/tokyonight_night.gitconfig"
  "${HOME}/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/eza/tokyonight_night.yml"
  "${HOME}/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/fzf/tokyonight_night.sh"
  "${HOME}/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/sublime/tokyonight_night.tmTheme"
)

print -P "%B--- zsh healthcheck ---%b"
print -P "%BChecking for required commands and files...%b"

# Check Commands
for cmd in $critical_cmds; do
  if (( $+commands[$cmd] )); then
    print -P "  %F{green}✔%f $cmd"
  else
    print -P "  %F{red}✘ $cmd (missing)%f"
    ((missing++))
  fi
done

# Check Files
for file in $critical_files; do
  if [[ -f $file ]]; then
    print -P "  %F{green}✔%f ${file}"
  else
    print -P "  %F{red}✘ ${file} (missing)%f"
    ((missing++))
  fi
done

[[ $missing -eq 0 ]] && print -P "\n%F{green}✅ All required commands and files are available.%f"

# Calculate load time
# Format the pre-calculated duration
local elapsed=$(printf "%.2f" $ZSH_LOAD_DURATION)

print -P "\n%B--- performance ---%b"
if (( elapsed < 50 )); then
  print -P "%F{green}🚀 zsh load time:%f ${elapsed}ms"
else
  print -P "%F{yellow}⚖️ zsh load time:%f ${elapsed}ms"
fi

