#!/usr/bin/env zsh

# Run 'zsh_healthcheck' manually to verify your setup
local missing=0

# Define your critical tools here
local critical_cmds=(nvim eza fzf zoxide delta)
local critical_dirs=(
  # installed via neovim plugin: https://github.com/folke/tokyonight.nvim
  "${XDG_DATA_HOME}/nvim/site/pack/core/opt/tokyonight.nvim/extras"
)
local critical_files=(
  # installed via homebrew (see ~/.config/brew)
  "${BREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
  "${BREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
)

print -P "%B--- zsh healthcheck ---%b"
print -P "%BChecking for required commands, dirs, and files...%b"

# Check Commands
for cmd in $critical_cmds; do
  if (( $+commands[$cmd] )); then
    print -P "  %F{green}✔%f $cmd"
  else
    print -P "  %F{red}✘ $cmd (missing command)%f"
    ((missing++))
  fi
done

# Check Dirs
for dir in $critical_dirs; do
  if [[ -d $dir ]]; then
    print -P "  %F{green}✔%f ${dir}"
  else
    print -P "  %F{red}✘ ${dir} (missing dir)%f"
    ((missing++))
  fi
done

# Check Files
for file in $critical_files; do
  if [[ -f $file ]]; then
    print -P "  %F{green}✔%f ${file}"
  else
    print -P "  %F{red}✘ ${file} (missing file)%f"
    ((missing++))
  fi
done

[[ $missing -eq 0 ]] && print -P "\n%F{green}✅ All required commands and files are available.%f"

# Calculate load time
# Format the pre-calculated duration
local elapsed=$(printf "%.2f" $ZSH_LOAD_DURATION)

print -P "\n%B--- performance ---%b"
if (( elapsed < 50 )); then
  print -P "%F{green}🚀 zsh load time:%f ${elapsed}ms"
else
  print -P "%F{yellow}⚖️ zsh load time:%f ${elapsed}ms"
fi

