#cloud-config

groups:
  - docker

users:
  - name: ubuntu
    groups: docker
    sudo: "ALL=(ALL) NOPASSWD:ALL"

bootcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc

apt:
  sources:
    docker.list:
      source: "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $RELEASE stable"

runcmd:
  - DEBIAN_FRONTEND=noninteractive apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

power_state:
  delay: "now"
  mode: "reboot"
  message: "Rebooting after cloud-init provisioning and updates"
  timeout: 30

